name: RSS Import

on:
  schedule:
    - cron: "17 * * * *"  # κάθε ώρα στο :17
  workflow_dispatch:

permissions:
  contents: write

jobs:
  import:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          persist-credentials: true

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run importer
        env:
          DEEPL_API_KEY: ${{ secrets.DEEPL_API_KEY }}
        run: |
          python scripts/rss_import.py

      - name: Git commit (if changes)
        run: |
          git config user.name "nba-eurozone-bot"
          git config user.email "actions@users.noreply.github.com"
          if [[ -n "$(git status --porcelain)" ]]; then
            git add -A
            git commit -m "chore(rss): hourly import $(date -u +'%Y-%m-%dT%H:%M:%SZ')"
            git push
          else
            echo "No changes to commit."
          fi
